version: "3.3"

services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    volumes:
      - mysqlvolume:/var/lib/mysql
    networks:
      - mynetwork
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - mynetwork
  shop:
    build:
      context: ./shop
      dockerfile: Dockerfile
    command: sh -c "npm run  start"
    depends_on:
      - mysql
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./shop:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
    ports:
      - 3000:3000
    networks:
      - mynetwork
volumes:
  mysqlvolume:

networks:
  mynetwork:
    external: false
